### ISSUE TITLE
Steps are not handled correctly

### ISSUE THREAD

**Issue by aklaer** [FFMbyBicycle/brouter-cycling-profiles#8]
It seems that the if clause does not handle steps as desired.
Probably only the 'not' needs to be shifted to ramp:wheelchair=yes?

```
if ( and not highway=steps ramp:wheelchair=yes ) then ( if allow_steps then 40 else 9999 )
  else if ( route=ferry   ) then ( if allow_ferries then 5.67 else 9999 )
```

**Comment by FFMbyBicycle** [comment]
Thanks for the report, this issue is already fixed: https://github.com/FFMbyBicycle/brouter-cycling-profiles/commit/eb7f08ab435c6a3d6adf929ff184cc4ca5ab91ea

You may try to insert the [latest version of my profile](https://github.com/FFMbyBicycle/brouter-cycling-profiles/blob/release/FFMbyBicycle-long-distance-cycling.brf) for now, until this version will be available i.e. at bikerouter :-)

Please feel free to comment or re-open this issue if there is still something or unclear.

**Comment by FFMbyBicycle** [comment]
Update: the profile at bikerouter.de was updated now, please test it again
